/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package LibDL.data;

import LibDL.SWIGTYPE_p_torch__data__ExampleT_at__Tensor_at__Tensor_t;
import LibDL.Tensor;

public class Example {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  public Example(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(Example obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        LibDL.ExampleModuleJNI.delete_data_Example(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public Tensor getData() {
    long cPtr = LibDL.ExampleModuleJNI.data_Example_data_get(swigCPtr, this);
    return (cPtr == 0) ? null : new Tensor(cPtr, false);
  }

  public Tensor getTarget() {
    long cPtr = LibDL.ExampleModuleJNI.data_Example_target_get(swigCPtr, this);
    return (cPtr == 0) ? null : new Tensor(cPtr, false);
  }

  public Example(SWIGTYPE_p_torch__data__ExampleT_at__Tensor_at__Tensor_t core) {
    this(LibDL.ExampleModuleJNI.new_data_Example(SWIGTYPE_p_torch__data__ExampleT_at__Tensor_at__Tensor_t.getCPtr(core)), true);
  }

}
