/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package LibDL.data;

import LibDL.SWIGTYPE_p_MNIST_PTR;

public class MNISTDataLoader implements java.lang.Iterable<LibDL.data.Example> {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  public MNISTDataLoader(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(MNISTDataLoader obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        LibDL.MNISTDataLoaderModuleJNI.delete_data_MNISTDataLoader(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public MNISTDataLoader(boolean train) {
    this(LibDL.MNISTDataLoaderModuleJNI.new_data_MNISTDataLoader(train), true);
  }

  public LibDL.data.MNISTDataIterator iterator() {
    long cPtr = LibDL.MNISTDataLoaderModuleJNI.data_MNISTDataLoader_iterator(swigCPtr, this);
    return (cPtr == 0) ? null : new LibDL.data.MNISTDataIterator(cPtr, false);
  }

}
