/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package LibDL.data;

import LibDL.SWIGTYPE_p_MNIST_PTR;

public class MNISTDataIterator implements java.util.Iterator<LibDL.data.Example> {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  public MNISTDataIterator(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(MNISTDataIterator obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        LibDL.MNISTDataIteratorModuleJNI.delete_data_MNISTDataIterator(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void remove() throws UnsupportedOperationException {
    throw new UnsupportedOperationException();
  }

  public LibDL.data.Example next() throws java.util.NoSuchElementException {
    if (!hasNext()) {
      throw new java.util.NoSuchElementException();
    }

    return nextImpl();
  }

  public MNISTDataIterator(SWIGTYPE_p_MNIST_PTR mnistPtr) {
    this(LibDL.MNISTDataIteratorModuleJNI.new_data_MNISTDataIterator(SWIGTYPE_p_MNIST_PTR.getCPtr(mnistPtr)), true);
  }

  public boolean hasNext() {
    return LibDL.MNISTDataIteratorModuleJNI.data_MNISTDataIterator_hasNext(swigCPtr, this);
  }

  public LibDL.data.Example nextImpl() {
    return new LibDL.data.Example(LibDL.MNISTDataIteratorModuleJNI.data_MNISTDataIterator_nextImpl(swigCPtr, this), true);
  }

}
