/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package LibDL;

public class Conv2dModuleJNI {
  public final static native long new_nn_Conv2d(int jarg1, int jarg2, int jarg3);
  public final static native long nn_Conv2d_getCore(long jarg1, LibDL.nn.Conv2d jarg1_);
  public final static native void delete_nn_Conv2d(long jarg1);
}
