/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package LibDL;

public class ExampleModuleJNI {
  public final static native long data_Example_data_get(long jarg1, LibDL.data.Example jarg1_);
  public final static native long data_Example_target_get(long jarg1, LibDL.data.Example jarg1_);
  public final static native long new_data_Example(long jarg1);
  public final static native void delete_data_Example(long jarg1);
}
