/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package LibDL;

public class LinearModuleTypeModuleJNI {
  public final static native void nn_LinearModuleType_core_set(long jarg1, LibDL.nn.LinearModuleType jarg1_, long jarg2);
  public final static native long nn_LinearModuleType_core_get(long jarg1, LibDL.nn.LinearModuleType jarg1_);
  public final static native long new_nn_LinearModuleType__SWIG_0();
  public final static native long nn_LinearModuleType_forward(long jarg1, LibDL.nn.LinearModuleType jarg1_, long jarg2, Tensor jarg2_);
  public final static native long new_nn_LinearModuleType__SWIG_1(long jarg1);
  public final static native void delete_nn_LinearModuleType(long jarg1);
}
