/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package LibDL;

public class LinearModuleJNI {
  public final static native long new_nn_Linear(int jarg1, int jarg2);
  public final static native long nn_Linear_forward(long jarg1, LibDL.nn.Linear jarg1_, long jarg2, Tensor jarg2_);
  public final static native void nn_Linear_print(long jarg1, LibDL.nn.Linear jarg1_);
  public final static native long nn_Linear_w(long jarg1, LibDL.nn.Linear jarg1_);
  public final static native long nn_Linear_b(long jarg1, LibDL.nn.Linear jarg1_);
  public final static native long nn_Linear_getCore(long jarg1, LibDL.nn.Linear jarg1_);
  public final static native void delete_nn_Linear(long jarg1);
}
