/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package LibDL;

public class MNISTDataIteratorModuleJNI {
  public final static native long new_data_MNISTDataIterator(long jarg1);
  public final static native boolean data_MNISTDataIterator_hasNext(long jarg1, LibDL.data.MNISTDataIterator jarg1_);
  public final static native long data_MNISTDataIterator_nextImpl(long jarg1, LibDL.data.MNISTDataIterator jarg1_);
  public final static native void delete_data_MNISTDataIterator(long jarg1);
}
