/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package LibDL;

public class MNISTDataLoaderModuleJNI {
  public final static native long new_data_MNISTDataLoader(boolean jarg1);
  public final static native long data_MNISTDataLoader_iterator(long jarg1, LibDL.data.MNISTDataLoader jarg1_);
  public final static native void delete_data_MNISTDataLoader(long jarg1);
}
