/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package LibDL;

public class ModuleModuleJNI {
  public final static native long nn_Module_register_linear_module(long jarg1, LibDL.nn.Module jarg1_, String jarg2, long jarg3, LibDL.nn.Linear jarg3_);
  public final static native long nn_Module_register_conv2d_module(long jarg1, LibDL.nn.Module jarg1_, String jarg2, long jarg3, LibDL.nn.Conv2d jarg3_);
  public final static native long nn_Module_parameters(long jarg1, LibDL.nn.Module jarg1_);
  public final static native void nn_Module_train(long jarg1, LibDL.nn.Module jarg1_);
  public final static native void nn_Module_eval(long jarg1, LibDL.nn.Module jarg1_);
  public final static native long new_nn_Module();
  public final static native void delete_nn_Module(long jarg1);
}
