/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package LibDL;

public class SGDModuleJNI {
  public final static native long new_optim_SGD(long jarg1, double jarg2);
  public final static native void optim_SGD_zero_grad(long jarg1, LibDL.optim.SGD jarg1_);
  public final static native void optim_SGD_step(long jarg1, LibDL.optim.SGD jarg1_);
  public final static native void delete_optim_SGD(long jarg1);
}
