/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package LibDL;

public class Tensor {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  public Tensor(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(Tensor obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        TensorModuleJNI.delete_Tensor(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public Tensor() {
    this(TensorModuleJNI.new_Tensor__SWIG_0(), true);
  }

  public Tensor(SWIGTYPE_p_torch__Tensor core) {
    this(TensorModuleJNI.new_Tensor__SWIG_1(SWIGTYPE_p_torch__Tensor.getCPtr(core)), true);
  }

  public Tensor add(Tensor other) {
    return new Tensor(TensorModuleJNI.Tensor_add(swigCPtr, this, Tensor.getCPtr(other), other), true);
  }

  public Tensor reshape(int[] size) {
    return new Tensor(TensorModuleJNI.Tensor_reshape(swigCPtr, this, size), true);
  }

  public Tensor view(int[] size) {
    return new Tensor(TensorModuleJNI.Tensor_view(swigCPtr, this, size), true);
  }

  public int size(int dim) {
    return TensorModuleJNI.Tensor_size(swigCPtr, this, dim);
  }

  public void print() {
    TensorModuleJNI.Tensor_print(swigCPtr, this);
  }

  public void backward() {
    TensorModuleJNI.Tensor_backward(swigCPtr, this);
  }

  public float item() {
    return TensorModuleJNI.Tensor_item(swigCPtr, this);
  }

  public void setCore(SWIGTYPE_p_torch__Tensor value) {
    TensorModuleJNI.Tensor_core_set(swigCPtr, this, SWIGTYPE_p_torch__Tensor.getCPtr(value));
  }

  public SWIGTYPE_p_torch__Tensor getCore() {
    return new SWIGTYPE_p_torch__Tensor(TensorModuleJNI.Tensor_core_get(swigCPtr, this), true);
  }

}
