/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package LibDL.optim;

import LibDL.SWIGTYPE_p_std__vectorT_at__Tensor_t;

public class SGD {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  public SGD(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(SGD obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        LibDL.SGDModuleJNI.delete_optim_SGD(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public SGD(SWIGTYPE_p_std__vectorT_at__Tensor_t parameters, double learning_rate) {
    this(LibDL.SGDModuleJNI.new_optim_SGD(SWIGTYPE_p_std__vectorT_at__Tensor_t.getCPtr(parameters), learning_rate), true);
  }

  public void zero_grad() {
    LibDL.SGDModuleJNI.optim_SGD_zero_grad(swigCPtr, this);
  }

  public void step() {
    LibDL.SGDModuleJNI.optim_SGD_step(swigCPtr, this);
  }

}
