/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package LibDL.nn;

import LibDL.SWIGTYPE_p_std__shared_ptrT_torch__nn__LinearImpl_t;
import LibDL.Tensor;

public class LinearModuleType {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  public LinearModuleType(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(LinearModuleType obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        LibDL.LinearModuleTypeModuleJNI.delete_nn_LinearModuleType(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setCore(SWIGTYPE_p_std__shared_ptrT_torch__nn__LinearImpl_t value) {
    LibDL.LinearModuleTypeModuleJNI.nn_LinearModuleType_core_set(swigCPtr, this, SWIGTYPE_p_std__shared_ptrT_torch__nn__LinearImpl_t.getCPtr(value));
  }

  public SWIGTYPE_p_std__shared_ptrT_torch__nn__LinearImpl_t getCore() {
    return new SWIGTYPE_p_std__shared_ptrT_torch__nn__LinearImpl_t(LibDL.LinearModuleTypeModuleJNI.nn_LinearModuleType_core_get(swigCPtr, this), true);
  }

  public LinearModuleType() {
    this(LibDL.LinearModuleTypeModuleJNI.new_nn_LinearModuleType__SWIG_0(), true);
  }

  public Tensor forward(Tensor self) {
    return new Tensor(LibDL.LinearModuleTypeModuleJNI.nn_LinearModuleType_forward(swigCPtr, this, Tensor.getCPtr(self), self), true);
  }

  public LinearModuleType(SWIGTYPE_p_std__shared_ptrT_torch__nn__LinearImpl_t core) {
    this(LibDL.LinearModuleTypeModuleJNI.new_nn_LinearModuleType__SWIG_1(SWIGTYPE_p_std__shared_ptrT_torch__nn__LinearImpl_t.getCPtr(core)), true);
  }

}
