/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package LibDL.nn;

import LibDL.Tensor;
import LibDL.SWIGTYPE_p_std__shared_ptrT_torch__nn__LinearImpl_t;

public class Linear {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  public Linear(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(Linear obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        LibDL.LinearModuleJNI.delete_nn_Linear(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public Linear(int in, int out) {
    this(LibDL.LinearModuleJNI.new_nn_Linear(in, out), true);
  }

  public Tensor forward(Tensor self) {
    return new Tensor(LibDL.LinearModuleJNI.nn_Linear_forward(swigCPtr, this, Tensor.getCPtr(self), self), true);
  }

  public void print() {
    LibDL.LinearModuleJNI.nn_Linear_print(swigCPtr, this);
  }

  public Tensor w() {
    return new Tensor(LibDL.LinearModuleJNI.nn_Linear_w(swigCPtr, this), true);
  }

  public Tensor b() {
    return new Tensor(LibDL.LinearModuleJNI.nn_Linear_b(swigCPtr, this), true);
  }

  public SWIGTYPE_p_std__shared_ptrT_torch__nn__LinearImpl_t getCore() {
    return new SWIGTYPE_p_std__shared_ptrT_torch__nn__LinearImpl_t(LibDL.LinearModuleJNI.nn_Linear_getCore(swigCPtr, this), true);
  }

}
